---
- name: Converge
  hosts: all
  become: true

  vars:
    docker_users:
      - abdullah

  pre_tasks:
    - name: create testing user
      ansible.builtin.user:
        name: {{ item }}
      loop: {{ docker_users }}

  roles:
    - role: abarrak.rhel_docker_server

  post_tasks:
    - name: Verify docker server is running.
      command: "systemctl is-active docker.service"
      changed_when: false
      become: true
      become_user: root
