---
- name: Converge
  hosts: all
  become: true
  vars:
    ansible_remote_tmp: /tmp
    docker_users:
      - abdullah

  pre_tasks:
    - name: Create testing user
      ansible.builtin.user:
        name: "{{ item }}"
      loop: "{{ docker_users }}"

  roles:
    - role: abarrak.docker_server_role

  post_tasks:
    - name: Verify docker server is running.
      command: "systemctl is-active docker.service"
      changed_when: false
      failed_when: false
      become: true
